// Code generated by go generate; DO NOT EDIT.

package version

var (
	Version   = "0.1.0"
	CommitSHA = "d3fc6419913e06e042af672ae926217845974ab0"
	BuildDate = "2026-06-30T16:34:31Z"
	BuildInfo = "dirty"
)
