// Code generated by go generate; DO NOT EDIT.

package version

var (
	Version   = "0.1.0"
	CommitSHA = "ec869e29625706241546fd2e98364606586b5f67"
	BuildDate = "2026-06-30T14:13:17Z"
	BuildInfo = "dirty"
)
