// Code generated by go generate; DO NOT EDIT.

package version

var (
	Version   = "0.1.0"
	CommitSHA = "7f066afae0fef92655024a792a8ca30dc1e806f8"
	BuildDate = "2026-06-21T12:34:35Z"
	BuildInfo = "dirty"
)
